package com.quantiagents.app.Repository;

import android.util.Log;

import androidx.annotation.NonNull;

import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.android.gms.tasks.Task;
import com.google.android.gms.tasks.Tasks;
import com.google.firebase.firestore.CollectionReference;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.QueryDocumentSnapshot;
import com.google.firebase.firestore.QuerySnapshot;
import com.google.firebase.firestore.SetOptions;
import com.quantiagents.app.models.Event;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;

/**
 * Manages direct data access for Events in Firestore.
 * Handles CRUD operations (Create, Read, Update, Delete).
 */
public class EventRepository {

    private final CollectionReference context;

    /**
     * Constructs an EventRepository.
     * @param fireBaseRepository The base repository providing access to the Firestore collection.
     */
    public EventRepository(FireBaseRepository fireBaseRepository) {
        this.context = fireBaseRepository.getEventCollectionRef();
    }

    /**
     * Synchronously retrieves an Event by its unique ID.
     * <p>
     * This method blocks the calling thread until the database operation completes.
     * It includes safety checks for null or empty IDs to prevent crashes.
     * </p>
     *
     * @param eventId The unique identifier of the event.
     * @return The Event object if found, or null if not found or if an error occurs.
     */
    public Event getEventById(String eventId) {
        if (eventId == null || eventId.trim().isEmpty()) {
            Log.w("Firestore", "getEventById called with null or empty ID");
            return null;
        }

        try {
            DocumentSnapshot snapshot = Tasks.await(context.document(eventId).get());
            if (snapshot.exists()) {
                Event event = snapshot.toObject(Event.class);
                if (event != null && (event.getEventId() == null || event.getEventId().trim().isEmpty())) {
                    event.setEventId(snapshot.getId());
                }
                return event;
            } else {
                Log.d("Firestore", "No event found for ID: " + eventId);
                return null;
            }
        } catch (IllegalArgumentException e) {
            Log.e("Firestore", "Invalid argument for event ID: " + eventId, e);
            return null;
        } catch (Exception e) {
            Log.e("Firestore", "Error getting event", e);
            return null;
        }
    }

    /**
     * Synchronously retrieves all events in the collection.
     * <p>
     * This method blocks the calling thread.
     * </p>
     *
     * @return A list of all Event objects found in the database.
     */
    public List<Event> getAllEvents() {
        try {
            QuerySnapshot snapshot = Tasks.await(context.get());
            List<Event> events = new ArrayList<>();
            for (QueryDocumentSnapshot document : snapshot) {
                Event event = document.toObject(Event.class);
                if (event != null) {
                    if (event.getEventId() == null || event.getEventId().trim().isEmpty()) {
                        event.setEventId(document.getId());
                    }
                    events.add(event);
                }
            }
            return events;
        } catch (Exception e) {
            Log.e("Firestore", "Error getting all events", e);
            return new ArrayList<>();
        }
    }

    /**
     * Asynchronously retrieves all events in the collection.
     *
     * @param onSuccess Callback invoked with the List of Events upon success.
     * @param onFailure Callback invoked with the Exception upon failure.
     */
    public void getAllEvents(OnSuccessListener<List<Event>> onSuccess, OnFailureListener onFailure) {
        context.get()
                .addOnSuccessListener(qs -> {
                    List<Event> out = new ArrayList<>();
                    for (QueryDocumentSnapshot d : qs) {
                        Event e = d.toObject(Event.class);
                        if (e != null) {
                            if (e.getEventId() == null || e.getEventId().trim().isEmpty()) {
                                e.setEventId(d.getId());
                            }
                            out.add(e);
                        }
                    }
                    onSuccess.onSuccess(out);
                })
                .addOnFailureListener(onFailure);
    }

    /**
     * Saves a new Event or updates an existing one if the ID matches.
     * <p>
     * If the Event object has no ID, one will be auto-generated by Firestore,
     * and the Event object will be updated with this new ID.
     * </p>
     *
     * @param event     The Event object to save.
     * @param onSuccess Callback invoked with the Event ID upon success.
     * @param onFailure Callback invoked with the Exception upon failure.
     */
    public void saveEvent(Event event, OnSuccessListener<String> onSuccess, OnFailureListener onFailure) {
        if (event.getEventId() == null || event.getEventId().trim().isEmpty()) {
            Task<DocumentReference> addTask = context.add(event);
            addTask.addOnSuccessListener(documentReference -> {
                String docId = documentReference.getId();
                String generatedId = docId;
                event.setEventId(generatedId);
                context.document(docId).update("eventId", generatedId)
                        .addOnSuccessListener(aVoid -> onSuccess.onSuccess(generatedId))
                        .addOnFailureListener(e -> onSuccess.onSuccess(generatedId));
            }).addOnFailureListener(onFailure);
        } else {
            String eventId = event.getEventId();
            context.document(eventId).set(event, SetOptions.merge())
                    .addOnSuccessListener(aVoid -> onSuccess.onSuccess(eventId))
                    .addOnFailureListener(onFailure);
        }
    }

    /**
     * Updates an existing Event in Firestore.
     * <p>
     * Performs a merge, updating only fields present in the object.
     * </p>
     *
     * @param event     The Event object with updated data.
     * @param onSuccess Callback invoked upon successful update.
     * @param onFailure Callback invoked with the Exception upon failure.
     */
    public void updateEvent(@NonNull Event event, @NonNull OnSuccessListener<Void> onSuccess, @NonNull OnFailureListener onFailure) {
        context.document(event.getEventId())
                .set(event, SetOptions.merge())
                .addOnSuccessListener(aVoid -> onSuccess.onSuccess(aVoid))
                .addOnFailureListener(onFailure);
    }

    /**
     * Asynchronously deletes an event by its ID.
     *
     * @param eventId   The ID of the event to delete.
     * @param onSuccess Callback invoked upon successful deletion.
     * @param onFailure Callback invoked upon failure.
     */
    public void deleteEventById(String eventId, OnSuccessListener<Void> onSuccess, OnFailureListener onFailure) {
        context.document(eventId)
                .delete()
                .addOnSuccessListener(onSuccess)
                .addOnFailureListener(onFailure);
    }

    /**
     * Synchronously deletes an event by its ID.
     *
     * @param eventId The ID of the event to delete.
     * @return True if the deletion was successful (or no error occurred), false otherwise.
     */
    public boolean deleteEventById(String eventId) {
        try {
            Tasks.await(context.document(eventId).delete());
            return true;
        } catch (Exception e) {
            Log.e("Firestore", "Error deleting event", e);
            return false;
        }
    }
}